FROM cbioportal/cbioportal:3.1.9
MAINTAINER Alexandros Sigaras <als2076@med.cornell.edu>, Fedde Schaeffer <fedde@thehyve.nl>
LABEL Description="cBioPortal for Cancer Genomics"
ENV APP_NAME="##CBIOPORTAL_NAME##-webapp" \
    PORTAL_HOME="/##CBIOPORTAL_NAME##"
#======== Install Prerequisites ===============#
RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        libmysql-java \
        patch \
        python3 \
        python3-jinja2 \
        python3-mysqldb \
        python3-requests \
        maven \
        openjdk-8-jdk \
    && ln -s /usr/share/java/mysql-connector-java.jar "$CATALINA_HOME"/lib/ \
    && rm -rf $CATALINA_HOME/webapps/examples \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y vim less

#======== Configure cBioPortal ===========================#
#COPY src.cbioportal $PORTAL_HOME
WORKDIR $PORTAL_HOME
EXPOSE 8080

ADD src.cbioportal/pom.xml $PORTAL_HOME/
ADD src.cbioportal/app.json $PORTAL_HOME/
#ADD context.xml $CATALINA_HOME/conf/context.xml
#======== Build cBioPortal on Startup ===============#
ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

